# Generated by Django 3.0.4 on 2020-05-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200506_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='submition_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
