# Generated by Django 3.0.4 on 2020-05-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_customerorder_submition_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
