# Generated by Django 3.0.6 on 2020-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_customerorder_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouseorder',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymouseorder',
            name='submition_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
