# Generated by Django 3.0.6 on 2020-05-12 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200512_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymouseorder',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='anonymouseorder',
            name='table_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='table_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anonymouseorder',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
